/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@code-dimension/stencil-components';
import {
  Config,
} from './lib/config';


export namespace Components {

  interface WarpViewEditor {
    'config': Config | string;
    'displayMessages': boolean;
    'heightLine': number;
    'heightPx': number;
    'horizontalLayout': boolean;
    'showDataviz': boolean;
    'showExecute': boolean;
    'tabbed': boolean;
    'theme': string;
    'url': string;
    'warpscript': string;
    'widthPx': number;
  }
  interface WarpViewEditorAttributes extends StencilHTMLAttributes {
    'config'?: Config | string;
    'displayMessages'?: boolean;
    'heightLine'?: number;
    'heightPx'?: number;
    'horizontalLayout'?: boolean;
    'onWarpViewEditorDatavizRequested'?: (event: CustomEvent) => void;
    'onWarpViewEditorErrorEvent'?: (event: CustomEvent) => void;
    'onWarpViewEditorLoaded'?: (event: CustomEvent) => void;
    'onWarpViewEditorStatusEvent'?: (event: CustomEvent) => void;
    'onWarpViewEditorWarpscriptChanged'?: (event: CustomEvent) => void;
    'onWarpViewEditorWarpscriptResult'?: (event: CustomEvent) => void;
    'showDataviz'?: boolean;
    'showExecute'?: boolean;
    'tabbed'?: boolean;
    'theme'?: string;
    'url'?: string;
    'warpscript'?: string;
    'widthPx'?: number;
  }

  interface WarpViewRawResult {
    'config': object;
    'heightLine': number;
    'heightPx': number;
    'result': any[];
    'theme': string;
  }
  interface WarpViewRawResultAttributes extends StencilHTMLAttributes {
    'config'?: object;
    'heightLine'?: number;
    'heightPx'?: number;
    'result'?: any[];
    'theme'?: string;
  }

  interface WarpViewResult {
    'config': object;
    'result': any[];
    'theme': string;
  }
  interface WarpViewResultAttributes extends StencilHTMLAttributes {
    'config'?: object;
    'result'?: any[];
    'theme'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WarpViewEditor': Components.WarpViewEditor;
    'WarpViewRawResult': Components.WarpViewRawResult;
    'WarpViewResult': Components.WarpViewResult;
  }

  interface StencilIntrinsicElements {
    'warp-view-editor': Components.WarpViewEditorAttributes;
    'warp-view-raw-result': Components.WarpViewRawResultAttributes;
    'warp-view-result': Components.WarpViewResultAttributes;
  }


  interface HTMLWarpViewEditorElement extends Components.WarpViewEditor, HTMLStencilElement {}
  var HTMLWarpViewEditorElement: {
    prototype: HTMLWarpViewEditorElement;
    new (): HTMLWarpViewEditorElement;
  };

  interface HTMLWarpViewRawResultElement extends Components.WarpViewRawResult, HTMLStencilElement {}
  var HTMLWarpViewRawResultElement: {
    prototype: HTMLWarpViewRawResultElement;
    new (): HTMLWarpViewRawResultElement;
  };

  interface HTMLWarpViewResultElement extends Components.WarpViewResult, HTMLStencilElement {}
  var HTMLWarpViewResultElement: {
    prototype: HTMLWarpViewResultElement;
    new (): HTMLWarpViewResultElement;
  };

  interface HTMLElementTagNameMap {
    'warp-view-editor': HTMLWarpViewEditorElement
    'warp-view-raw-result': HTMLWarpViewRawResultElement
    'warp-view-result': HTMLWarpViewResultElement
  }

  interface ElementTagNameMap {
    'warp-view-editor': HTMLWarpViewEditorElement;
    'warp-view-raw-result': HTMLWarpViewRawResultElement;
    'warp-view-result': HTMLWarpViewResultElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
